### ISSUE TITLE
Separate class for name monster?

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#1]
Have u considered a separate class to isolate the messy namespace -- do all the other logic traditionally and just the brian flat code generation inside an isolated "name_monster"?

**Comment by Vafa-Andalibi** [comment]
I need more information on this and/or examples for before/after

**Comment by Vafa-Andalibi** [comment]
@sivanni is this addressed in the package folder/file re-organization?

**Comment by sivanni** [comment]
Sorry for being imprecise, and let me know if I am wrong. Within the cxsystem.py module brian2 namespace is imported via from cxsystem2.core.stimuli import * . This results in thousands of names in the module's namespace. If brain2 could be imported as br this would be resolved. For units, it may be necessary to use the original units and not eg br.mm etc, and this is acceptable. So the solution could be: import units from brian as is, but import the rest of brian commands as br .
