### ISSUE TITLE
Dynamic list of neuron subtypes

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#11]
The neuron_subtype refers to a certain set of parameters in the physio configuration file. There's no point in making a fixed list of subtypes in the JSON schema. Can we make the UI dynamically update the list of possible subtypes?

**Comment by Vafa-Andalibi** [comment]
Does this mean we need the subtype to be similar to dropdown menu? Or just manually-typed string (as is right now? 
If the former, then do we have a list of all possible subtypes anywhere? 
If the latter, the issue should be closed.

**Comment by henhok** [comment]
Let's leave it as it for now
