### ISSUE TITLE
Out of memory when running Markram model step 1 on cpp device

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#14]

**Comment by henhok** [comment]
This was on Pikkuveli with plenty of mem.

**Comment by Vafa-Andalibi** [comment]
Did this happen when running with GUI?

**Comment by henhok** [comment]
No GUI, plain old CxSystem.

**Comment by Vafa-Andalibi** [comment]
This model seems to be pretty huge. Isn't this much bigger than the Markram than the simplified model? 

Also when does it go out of memory? During compilation?

**Comment by henhok** [comment]
Yes, this is the bigger simplified model the referee requested (step 1). I will test it again, it might be related to Brian's parallel compilation issue in Linux.

**Comment by henhok** [comment]
The issue was due to Brian's parallel compilation issue in Linux
