### ISSUE TITLE
JSON output from config_file_converter is not human-readable

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#22]
Needs more whitespace

**Comment by Vafa-Andalibi** [comment]
Is this about the `get_json()` or the saved JSON file?

**Comment by henhok** [comment]
Saved json file, using converter.save_as_json()

**Comment by Vafa-Andalibi** [comment]
I was assuming that the user can rely on JSON formatter of their editor. In Pycharm it's `Ctrl + Alt + L` , in VSCode it's `Shift+Alt+F` , in `notepad++` it should be `Ctrl + Alt + Shift + B` . Which editor do you use?

**Comment by henhok** [comment]
Ok, that's fine :)

**Comment by Vafa-Andalibi** [comment]
Also, for the record when you want to print the JSON configs in python , you can use the `pprint` to get a clear view:

```
from pprint import pprint 
pprint( json_variable_or_dict ) 
```
