### ISSUE TITLE
pytest config files changed

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#28]
The test config files have been changed and pytest cannot be run anymore. It fails with trials_per_config 2, which causes proble with password extraction from somewhere.

**Comment by Vafa-Andalibi** [comment]
Fixed in e708172a2723391f49556dc9dc5464fed43b750e

**Comment by Vafa-Andalibi** [comment]
For the record, all the tests are passing on windows 10 after some update in 8ab4a0bf944be77ef7766ae714996e807536f591
