### ISSUE TITLE
Add cython to list of devices

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#30]
Our list of devices includes Python, Cpp and Genn. "Python" should refer to Numpy-Python (prefs.codegen.target = 'numpy'), which always works, and Cython would then refer to Cython-Python (prefs.codegen.target = 'cython'), which can be faster sometimes.

**Comment by Vafa-Andalibi** [comment]
Fixed in 540daa6d05d559a7f85b094dffadade3c87137c3
