### ISSUE TITLE
In windows Cpp device gives error 

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#32]
The error is "OSError: Cannot find vcvarsall.bat on standard search path. Set the codegen.cpp.msvc_vars_location preference explicitly" 
I have installed and reinstalled Visual Studio 2019, set the path environment variable to point to vcvarsall.bat folder.
The Brian 2.0.XX version listed this error and suggested turning off OpenMP, but the current 2.2.2.1 not anymore.
Because it is specific for Windows and Cpp, so this issue has low priority.

**Comment by Vafa-Andalibi** [comment]
This is most probably because you don't have the compiler on your machine. 
Can you try installing the Visual C++ Build Tools 2015? 
It's for instance available [here](https://www.microsoft.com/en-us/download/details.aspx?id=48159).
