### ISSUE TITLE
Create setup.py etc to allow installation via pip

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#4]
Just too many dependencies these days, can't remember them all

**Comment by sivanni** [comment]
Agree. If we can easily skip some of them, that would be nice, too.

**Comment by Vafa-Andalibi** [comment]
This can be done preferably after merge with develop and then master. Doing this will make the merge with develop difficult.

**Comment by Vafa-Andalibi** [comment]
Fixed in 67bb2f5:
`cxsystem2` package is now available on pip (early version 0.0.1). 
You can install it with `pip install cxsystem2`
