### ISSUE TITLE
After updating from develop, gui_test.py does not run

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#43]
Hi Guys, I tested the most recent version in windows10, by running gui_test.py and got the following (both chrom and firefox are unable to connect, directly running CxSystem without gui works):

(base) PS C:\Users\Simo\Laskenta\Git_Repos\CxSystem2> python .\gui_test.py
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: C:\Users\Simo\AppData\Local\Temp\brian_debug_vnbm6yrq.log  Additionally, you can also include a copy of the script that was run, available at: C:\Users\Simo\AppData\Local\Temp\brian_script_btfvdx6b.py Thanks! [brian2]
Traceback (most recent call last):
  File ".\gui_test.py", line 3, in <module>
    CxSystem()
  File "C:\Users\Simo\Laskenta\Git_Repos\CxSystem2\CxSystem.py", line 90, in __init__
    self.runGUI()
  File "C:\Users\Simo\Laskenta\Git_Repos\CxSystem2\CxSystem.py", line 247, in runGUI
    gui.runserver(port = self.port)
  File "C:\Users\Simo\Laskenta\Git_Repos\CxSystem2\CxGUI\gui.py", line 28, in __init__
    chrome = webbrowser.get('chrome')
  File "C:\Users\Simo\Miniconda3\lib\webbrowser.py", line 65, in get
    raise Error("could not locate runnable browser")
webbrowser.Error: could not locate runnable browser

**Comment by Vafa-Andalibi** [comment]
There was a minor bug in running the django server, fixed in 1b9776d
