### ISSUE TITLE
Button for deleting currently active tab

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#45]
Now in Inputs, NeuronGroups, Connections and Physiology, only the last element can be deleted. There should be a button for deleting the currently selected element. Also, the confirmation message should tell which element the user is about to delete.

**Comment by Vafa-Andalibi** [comment]
For physiology the button existed in the bottom of the page. There was a bug for NeuronGroup and Connections which is fixed now. The "delete current entry" is at the bottom.
