### ISSUE TITLE
Command line app for fetching results from HPCs

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#48]
We discussed this with @Vafa-Andalibi on Hangouts. 
- Companion app for cluster_run (which sends the jobs)
- The GUI provides the user with metadata for fetching results
- User can then fetch simulation results on their local computer (or for demonstration, to jupyter notebook kernel storage inside the Brain Simulation Platform; we will create an example notebook)

**Comment by Vafa-Andalibi** [comment]
Implemented in 5d102b595566bcc691ebe387f4d2e5fa3c89ea08
