### ISSUE TITLE
Grid_radius is not grid radius?

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#50]
Looking at cell positions in this example with grid_radius set to 210 um makes me wonder what is grid_radius actually referring to... If it was radius, then min+max = ~420 um. If it was diameter, then min+max = ~210 um. Right? 

![grid_radius](https://user-images.githubusercontent.com/18504377/67104719-1f2c4f80-f1d0-11e9-9d68-47316baf0030.png)

**Comment by Vafa-Andalibi** [comment]
@sivanni can you check this and confirm whether this is a bug?

**Comment by sivanni** [comment]
210 microm was the radius in Markram model, in above example it is diameter

Hanki Outlook for Android<https://aka.ms/ghei36>

________________________________

**Comment by sivanni** [comment]
Thus I think it might be a bug

**Comment by henhok** [comment]
My bad! Cell positions are stored in w_positions, not z_positions as shown in the picture above. z_positions correspond to retinal locations. I fixed visimpl conversion code and added comments to the code.
