### ISSUE TITLE
pip install issues

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#51]
Windows 10, 64 bit, installed pip install cxsystem, started with some delay ok, in console gave (same error with clean virtual environment)

Performing system checks...

System check identified no issues (0 silenced).

You have 17 unapplied migration(s). Your project may not work properly until you apply the migrations for app(s): admin, auth, contenttypes, sessions.
Run 'python manage.py migrate' to apply them.
October 19, 2019 - 15:30:27
Django version 2.2.6, using settings 'cx_gui.settings'
Starting development server at http://127.0.0.1:52885/
Quit the server with CTRL-BREAK.
c:\users\simo\miniconda3\lib\site-packages\cxsystem2
 -  Current run filename suffix is: 20191019_15312030
 -  The system is running with euler integration method
 -  System parameter remote_branch not defined.
 -  Brian Code Generator set to Numpy
 -  CxSystem is running on python device
 -  Membrane voltages are not initialized.
 -  Default clock is set to 100. us
 -  setting output path ...
 -  CxSystem is running in local mode
 -  Creating an input based on the central 60 neurons ...
 -  Customized VPM neuron in layer 0 initialized with 60 neurons.
 -  Customized PC neuron in layer [4, 1] initialized with 267 neurons.
 -  Customized PC neuron in layer [4, 1] initialized with 109 neurons.
 -  Customized SS neuron in layer 4 initialized with 40 neurons.
 -  Customized BC neuron in layer 4 initialized with 32 neurons.
 -  Customized MC neuron in layer 4 initialized with 13 neurons.
Process spawned_CxSystem:
Traceback (most recent call last):
  File "C:\Users\Simo\Miniconda3\lib\multiprocessing\process.py", line 297, in _bootstrap
    self.run()
  File "C:\Users\Simo\Miniconda3\lib\multiprocessing\process.py", line 99, in run
    self._target(*self._args, **self._kwargs)
  File "c:\users\simo\miniconda3\lib\site-packages\cxsystem2\gui\cx_gui\editor\views.py", line 36, in CxSpawner
    cm =  Cx(anatomy, physiology)
  File "C:\Users\Simo\Miniconda3\lib\site-packages\cxsystem2\core\cxsystem.py", line 232, in __init__
    self.configuration_executor()
  File "C:\Users\Simo\Miniconda3\lib\site-packages\cxsystem2\core\cxsystem.py", line 268, in configuration_executor
    self.parameter_to_method_mapping[self.anat_and_sys_conf_df.loc[self.value_line_idx, 0]][1]()
  File "C:\Users\Simo\Miniconda3\lib\site-packages\cxsystem2\core\cxsystem.py", line 1325, in synapse
    self._set_load_brian_data_path()
  File "C:\Users\Simo\Miniconda3\lib\site-packages\cxsystem2\core\cxsystem.py", line 530, in _set_load_brian_data_path
    ' -  The brian_data file cannot be found for loading: {}'.format(os.path.abspath(self.load_brian_data_path))
AssertionError:  -  The brian_data file cannot be found for loading: c:\users\simo\miniconda3\lib\site-packages\tests\connection_files\connections_20190517_06115909_python_200ms.gz

**Comment by Vafa-Andalibi** [comment]
I'm closing this because `CxSystem` had severe path issues at that point. It should be fixed now after the `workspace` implementation. Try installing version `0.0a40` and your faced other issues related to this, open another issue since the backtrace is now outdated.
