### ISSUE TITLE
CxSystem Workspace directory

### ISSUE THREAD

**Issue by Vafa-Andalibi** [VisualNeuroscience-UH/CxSystem2#53]
CxSystem needs a workspace directory otherwise the issues for relative paths will always persist.

**Comment by sivanni** [comment]
Agree, just make a suggestion. Clear modularity, clear self-explanatory folder names, clear self-explanatory module names, etc. Record decisions on any level to the Conventions

**Comment by Vafa-Andalibi** [comment]
Feature added in fc13a7aefb81279421e81f6dcfa5279a251fe96b
