### ISSUE TITLE
Saving setup cumbersome

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#55]
Saving conf should prompt for browsing filename , location. Now saving to downloaded folder with fixed name is cumbersome. Maybe enable saving with same name too, when modified. Low priority.

**Comment by Vafa-Andalibi** [comment]
Is this about the BUI?

**Comment by Vafa-Andalibi** [comment]
This is a browser configuration issue. This would solve that in chrome: 

```
- Click the menu icon in Chrome and click Settings.
- Scroll down and click “Show advances settings...”
- Scroll to the Downloads section.
- Click the “Ask where to save each file before downloading” toggle.
```
