### ISSUE TITLE
Re-organize files for clarity

### ISSUE THREAD

**Issue by henhok** [VisualNeuroscience-UH/CxSystem2#6]
Discussed with @sivanni that files should be re-organized similar to https://github.com/LFPy/LFPy for easier navigation

**Comment by Vafa-Andalibi** [comment]
This will be done after #4 , which will be done after merge.

**Comment by Vafa-Andalibi** [comment]
Fixed in 67bb2f58480a7549f1c4a9c3b5b6c7e3fbcf6257
