### ISSUE TITLE
Doc issues

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#68]
- [x] The basic CLI commands are not explained in documentation, only in GitHub
- [x] GeNN installation missing
- [x] User's guide; Anatomy; Init VMS unclear
- [ ] External input: thalamocortical fibers relative to origo (real and imaginary coordinates in deg, ?? e.g. [5 -0j]?
 
Physiology 
- [x] What is model variation? Why always True
- [x] In physiology config, cvs table include syntax "100 * pF". Should it be "100*pF" for correct syntax?
 
Batch simulations
- [ ] When multidimension_array_run flag is set to 0, example: What is the scale and init vms for each of the five simulations -- what is the rule. Ie how is the 1-dim search done? From the first param in each list?
  
Visualization
- [x] it is empty
	
Command line interface
- [x] it is empty
	
Running the BUI locally
- [x] it is empty
	
Technical overview
- [ ] is the globals() command used still in python 3? Did not find it in cxsystem.py module

**Comment by henhok** [comment]
- GeNN is automatically installed by pip (just another requirement)
- I tried to clarify init_vms, model_variation explanations
- In physio config, you can write 100*pF or 100 * pF, doesn't matter
- Visualization and running BUI now updated
