### ISSUE TITLE
cxvisualize does not find csv

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#71]
In isosisko, I made new work directory, ran pytest esample and tried to open visimpl for the .gz file, and got:
(CX2) sivanni@dx6-neuromancer:/opt3/CX2_wrkdir/sim_pytest$ cxvisualize sim_pytest_results_20191210_1533113.gz 
sh: 1: -csv: not found

**Comment by sivanni** [comment]
I wonder if these are enough (they are in path)
-rwxrwxrwx 1 sivanni hyad-all 35018363 Dec 10 17:39 stackviz-0.1.4-x86_64.dmg
-rwxrwxrwx 1 sivanni hyad-all 34493139 Dec 10 17:39 visimpl-0.1.4-x86_64.dmg

**Comment by Vafa-Andalibi** [comment]
fixed in b0579ca
