### ISSUE TITLE
Output path not saved to self when array run

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#8]
It would be good to have the output path saved to self object in cxsystem also with array run. Now it seems to skip the saving of the outputpath.

**Comment by Vafa-Andalibi** [comment]
The `output_path` is now changed to `workspace` and it's available with `cx.workspace.get_workspace_folder()` as `Path` object or `cx.workspace.get_workspace_folder_as_posix()` as string.
