### ISSUE TITLE
array_run.py exception not working

### ISSUE THREAD

**Issue by sivanni** [VisualNeuroscience-UH/CxSystem2#82]
Vafa -- check the last comment first to save time :) 
I run cxsystem2 from command line, but it gives error due to value error which it does not understand as int. This is probably easy to fix (and I will), but probably there is some logic which fails, too. So I will make the correction, but can u Vafa check it.

(simuenv) PS C:\Users\Simo\Laskenta\Models\SchwabeModel\config_files> cxsystem2 -a .\exported_anatomy_example_short.csv -p .\exported_physiology_example_short.csv
 -  Current run filename suffix is: 20191220_1115533
 -  The system is running with euler integration method
 -  simulation folder C:\Users\Simo\Laskenta\Models\SchwabeModel\test
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: C:\Users\Simo\AppData\Local\Temp\brian_debug_xkx0hqp1.log  Additionally, you can also include a copy of the script that was run, available at: C:\Users\Simo\AppData\Local\Temp\brian_script_2gao56o6.py Thanks! [brian2]
Traceback (most recent call last):
  File "c:/users/simo/laskenta/git_repos/cxsystem2/cxsystem2/hpc/array_run.py", line 429, in <module>
    ArrayRun(anatomy_df, physiology_df, suffix, cluster_start_idx, cluster_step, anat_file_address, physio_file_address, array_run_in_cluster, array_run_stdout_file)
  File "c:/users/simo/laskenta/git_repos/cxsystem2/cxsystem2/hpc/array_run.py", line 66, in __init__
    self.multidimension_array_run = int(parameter_finder(self.anatomy_df, 'multidimension_array_run'))
ValueError: invalid literal for int() with base 10: 'False'
(simuenv) PS C:\Users\Simo\Laskenta\Models\SchwabeModel\config_files> cxsystem2 -a .\exported_anatomy_example_short.csv -p .\exported_physiology_example_short.csv
 -  Current run filename suffix is: 20191220_1117250
 -  The system is running with euler integration method
 -  simulation folder C:\Users\Simo\Laskenta\Models\SchwabeModel\test
ERROR      Brian 2 encountered an unexpected error. If you think this is bug in Brian 2, please report this issue either to the mailing list at <http://groups.google.com/group/brian-development/>, or to the issue tracker at <https://github.com/brian-team/brian2/issues>. Please include this file with debug information in your report: C:\Users\Simo\AppData\Local\Temp\brian_debug_6nt26ge0.log  Additionally, you can also include a copy of the script that was run, available at: C:\Users\Simo\AppData\Local\Temp\brian_script_ducgbhuy.py Thanks! [brian2]
Traceback (most recent call last):
  File "c:/users/simo/laskenta/git_repos/cxsystem2/cxsystem2/hpc/array_run.py", line 429, in <module>
    ArrayRun(anatomy_df, physiology_df, suffix, cluster_start_idx, cluster_step, anat_file_address, physio_file_address, array_run_in_cluster, array_run_stdout_file)
  File "c:/users/simo/laskenta/git_repos/cxsystem2/cxsystem2/hpc/array_run.py", line 66, in __init__
    self.multidimension_array_run = int(parameter_finder(self.anatomy_df, 'multidimension_array_run'))
ValueError: invalid literal for int() with base 10: 'False'

**Comment by sivanni** [comment]
can be solved by int(eval('True')), by adding the eval. I will do it in my branch but can u Vafa pls check the logic

**Comment by sivanni** [comment]
The corrected versions are in branch macv1, if u can Vafa check and pull to master if u agree.

**Comment by Vafa-Andalibi** [comment]
merged in 8d56217a5d6e6e8193f779f886f2042027e96f5f
